import os

import ollama as oll

from . import models
from .. import config

from typing import Dict, List

LLM_CLIENT: oll.Client = oll.Client(host=os.getenv("OLLAMA_CONN_ENDPOINT"))

def call(
    messages: List[Dict],
) -> str:

    response: oll.ChatResponse = LLM_CLIENT.chat(
        model=config.LLM_MODEL,
        messages=messages,
    )

    return str(response.message.content)


def rerank(
    query: str,
    hits: List[Dict]
) -> List[Dict]:

    if not hits:
        return hits

    candidates_block = "\n".join(
        f"ID={h['id']}: {h['search_text'][:300]}" for h in hits
    )
    prompt = (
        f"Query: {query}\n\n"
        f"Rank the following candidates from most to least relevant.\n"
        f"Return a JSON object with a single key 'ranked_ids' containing an ordered list of candidate IDs.\n\n"
        f"{candidates_block}"
    )

    try:
        response: oll.ChatResponse = LLM_CLIENT.chat(
            model=config.LLM_MODEL,
            messages=[{"role": "user", "content": prompt}],
            format=models.RerankResult.model_json_schema(),
        )
        result = models.RerankResult.model_validate_json(response.message.content)
        id_to_hit: Dict[str, Dict] = {h["id"]: h for h in hits}
        reranked = [id_to_hit[rid] for rid in result.ranked_ids if rid in id_to_hit]
        seen = set(result.ranked_ids)
        reranked += [h for h in hits if h["id"] not in seen]
        return reranked
    except Exception:
        return hits


def evaluate(
    query: str,
    true_answers: List[str],
    generated_answer: str,

) -> models.LLMJudgeFormat:

    prompt = (
        f"Query from user (query): {query}"
        f"Actual people corresponding to the user's description (true_answers): {str(true_answers)} \n\n"
        f"Answer generated by the LLM (generated_answer): {generated_answer} \n\n"
        "Evaluate the generated answer using an ordinal ranking: "
        "(poor, insufficient, sufficient, good, excellent). "
        "It's important that you **ONLY** consider whether each mentioned person in "
        "the LLM's response is in the true_answers."
    )

    evaluation: oll.ChatResponse = LLM_CLIENT.chat(
        model=config.LLM_MODEL,
        messages=[{"role": "user", "content": prompt}],
        format=models.LLMJudgeFormat.model_json_schema(),
    )

    return evaluation






